dance/urls.py
from django.urls import path
from . import views

app_name = 'dance'

urlpatterns = [
    path('', views.dance_schedule_view, name='schedule'),
    path('wartung/', views.maintenance_view, name='maintenance'),
    path('lehrer-aktion/', views.teacher_action, name='teacher_action'),
    path('kurs-aktion/', views.course_action, name='course_action'),
    path('zeitfenster-aktion/', views.timeslot_action, name='timeslot_action'),
    path('loeschen/', views.delete_action, name='delete_action'),
    path('kurs/<int:course_id>/', views.course_detail, name='course_detail'),
    
    # Excel Import/Export
    path('excel-export/', views.export_excel, name='excel_export'),
    path('excel-import/', views.import_excel, name='excel_import'),
    
    # API-Endpunkte für die AJAX-Funktionalität
    path('api/lehrer/<int:teacher_id>/', views.teacher_detail_api, name='teacher_detail_api'),
    path('api/zeitfenster/<int:timeslot_id>/', views.timeslot_detail_api, name='timeslot_detail_api'),
]

faq/urls.py
from django.contrib import admin
from django.urls import path
from faq import views

urlpatterns = [
    path('faq', views.faq_view, name='faq_view'),
    path('edit/get-all-faqs', views.get_all_faqs, name='get_all_faqs'),
    path('edit/get-faq', views.get_faq, name='get_faq'),
    path('edit/create-faq', views.create_faq, name='create_faq'),
]

mks/urls.py
from django.contrib import admin
from django.views.generic import TemplateView
from django.urls import include, path, re_path
from django.conf.urls import handler404, handler500
from django.conf import settings
from django.conf.urls.static import static

import home.views
import teaching.views


admin.autodiscover()

from django.urls import include, re_path
from django.contrib import admin

from django.contrib.sitemaps.views import sitemap

from home.sitemaps import Static_Sitemap

sitemaps = {
    'static': Static_Sitemap(),
}


urlpatterns = [
    path('', include('maintenance.urls')),  # Wartungsmodus - muss als erstes kommen
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^blog/', include('blog.urls')),
    re_path(r'^blogedit/', include('blog.edit_urls')),
    re_path(r'^tinymce/', include('tinymce.urls')),  # Added TinyMCE URLs

#    re_path(r'^instruments/', include('instruments.urls')),
    path('', home.views.home, name='home_view'),
    path('impressum/', home.views.impressum, name='impressum'),
    path('geschichte/', home.views.history, name='history'),
    path('logo/', home.views.logo, name='logo'),
    path('team/', include('users.urls', namespace='users')),
    path('controlling/', include('controlling.urls', namespace='controlling')),
    path('', include('contact.urls')),
    path('', include('downloadsection.urls')),
    path('', include('gallery.urls')),
    path('lehrende/', include('teaching.urls', namespace='teaching')),
    # path('standorte/', include('location.urls', namespace='location')), 
    path('orgelunterricht/', teaching.views.orgelunterricht_view, name='orgelunterricht'),
    path('tanz-und-bewegung/', include('dance.urls', namespace='dance')),
    path('projekte/', include('projects.urls', namespace='projects')),
    path('', include('students.urls')),
    path('', include('faq.urls')),
    path('hexe-rabaukel/', include('invitation.urls')),
    path('midi-band/', include('midi_band.urls')),

    re_path(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'home.views.view_404'
handler500 = 'home.views.view_404'

#if settings.DEBUG:
#    import debug_toolbar
#    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

teaching/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic import TemplateView
from . import views
import teaching.get_students
from teaching.get_students import get_all_students, get_student
from teaching.show_teacher_view import show_teacher_view

app_name = 'teaching'

urlpatterns = [
    path('ueber-uns', teaching.show_teacher_view.show_teacher_view, name="all_teachers"),
    path('bildungsangebot-musikschule', teaching.views.teaching_music_view, name="teaching_music"),
    path('bildungsangebot-musikschule/blasinstrumente', teaching.views.teaching_brass_view, name="teaching_brass"),
    path('bildungsangebot-musikschule/elementare-musikerziehung', teaching.views.teaching_eme_view, name="teaching_eme"),
    path('bildungsangebot-musikschule/musikkunde', teaching.views.teaching_theory_view, name="teaching_theory"),
    path('bildungsangebot-musikschule/schlaginstrumente', teaching.views.teaching_drums_view, name="teaching_drums"),
    path('bildungsangebot-musikschule/stimmbildung', teaching.views.teaching_vocal_view, name="teaching_vocal"),
    path('bildungsangebot-musikschule/streichinstrumente', teaching.views.teaching_strings_view, name="teaching_strings"),
    path('bildungsangebot-musikschule/tasteninstrumente', teaching.views.teaching_keys_view, name="teaching_keys"),
    path('bildungsangebot-musikschule/zupfinstrumente', teaching.views.teaching_picked_view, name="teaching_picked"),
    path('bildungsangebot-musikschule/tanz-und-bewegung', teaching.views.teaching_dance_view, name="teaching_dance"),
    path('bildungsangebot-kunstschule', teaching.views.teaching_art_view, name="teaching_art"),
    path('beitraege-ermaessigungen', teaching.views.teaching_prices_view, name="teaching_prices"),
]

templates/templates/navbar.html
{% load static %}

<!-- NAV -->
<header>
  <div class="nvb">
    <div class="bnbs">
      <div class="bls">
        <a href="{% url 'home_view' %}">
          {% include "templates/svg/nav_bar_icon.html" %}
        </a>
      </div>
      <div class="bns">
        <div class="drops">
        <div class="dropdown arrow">
          <button class="dropbtn">
            <a href="{% url 'teaching:teaching_music'%}">Musikschule</a>
          </button>
          <div class="dropdown-content dropdown-wide">
            <div class="dropdown-columns">
              <div class="dropdown-column">
                <h3>Fachgruppen</h3>
                <a href="{% url 'teaching:teaching_brass'%}">Blasinstrumente</a>
                <a href="{% url 'teaching:teaching_eme'%}">Elementare Musikerziehung</a>
                <a href="{% url 'teaching:teaching_theory'%}">Musikkunde</a>
                <a href="{% url 'teaching:teaching_drums'%}">Schlaginstrumente</a>
              </div>
              <div class="dropdown-column">
                <h3>&nbsp;</h3>
                <a href="{% url 'teaching:teaching_vocal'%}">Stimmbildung</a>
                <a href="{% url 'teaching:teaching_strings'%}">Streichinstrumente</a>
                <a href="{% url 'dance:schedule'%}">Tanz & Bewegung</a>
                <a href="{% url 'teaching:teaching_keys'%}">Tasteninstrumente</a>
                <a href="{% url 'teaching:teaching_picked'%}">Zupfinstrumente</a>
              </div>
              <div class="dropdown-column">
                <h3>Weitere Angebote</h3>
                <a href="{% url 'orgelunterricht' %}">Orgelunterricht</a>
                <a href="{% url 'midi_band' %}">MIDI Band</a>
                <a href="{% url 'teaching:teaching_prices'%}">Beiträge & Ermäßigungen</a>
              </div>
            </div>
          </div>
          <div class="dropdown-hover-section">
          </div>
        </div>
        <div class="dropdown-b arrow">
          <button class="dropbtn-b">
            <a href="{% url 'teaching:teaching_art'%}">Kunstschule</a>
          </button>
          <div class="dropdown-hover-section-b">
          </div>
        </div>
        <div class="dropdown arrow">
          <button class="dropbtn">
            <a href="{% url 'gallery_view'%}">Galerie</a>
          </button>
          <div class="dropdown-hover-section-b">
          </div>
        </div>
        <div class="dropdown-d arrow">
          <button class="dropbtn-d">
            <a href="{% url 'teaching:all_teachers'%}">Über uns</a>
          </button>
          <div class="dropdown-content-d">
            <a href="{% url 'teaching:all_teachers'%}">Team</a>
            <a href="{% url 'history'%}">Geschichte</a>
            <a href="{% url 'blog_summary' %}">Blog</a>
          </div>
          <div class="dropdown-hover-section-d">
          </div>
        </div>
        <div class="dropdown-e arrow">
          <button class="dropbtn-e">
            <a href="{% url 'contact_email' %}">Kontakt</a>
          </button>
          <div class="dropdown-hover-section-e">
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Mobile Nav -->
  <div id="mks-nav-mobile" class="menu">
    <div>
      <span id="menuIcon" onclick="openNav()">
        {% include "templates/svg/nav_bar_hamburger_mobile.html" %}
      </span>
    </div>
    <div class="">
    </div>
    <div id="mobileLogo">
      <a id="small-mobile-logo" href="{% url 'home_view' %}">
        {% include "templates/svg/nav_bar_mobile_logo.html" %}
      </a>
      <a id="medium-mobile-logo" href="{% url 'home_view' %}">
        {% include "templates/svg/nav_bar_icon.html" %}
      </a>
    </div>
  </div>
  <div id="mks-nav-mobile-menu" class="overlay">
    <div class="overlay-content">
      <a id="closeMobileMenu" href="javascript:void(0)" class="closebtn" onclick="closeNav()">
        {% include "templates/svg/nav_bar_cross_burger.html" %}
      </a>
      
      <!-- Musikschule Gruppe -->
      <div class="mobile-nav-group">
        <a class="mobile-main-heading" href="{% url 'teaching:teaching_music'%}">
          Musikschule
        </a>
        <div class="mobile-sub-items">
          <div class="mobile-section-divider">Fachgruppen</div>
          <a href="{% url 'teaching:teaching_brass'%}">Blasinstrumente</a>
          <a href="{% url 'teaching:teaching_eme'%}">Elementare Musikerziehung</a>
          <a href="{% url 'teaching:teaching_theory'%}">Musikkunde</a>
          <a href="{% url 'teaching:teaching_drums'%}">Schlaginstrumente</a>
          <a href="{% url 'teaching:teaching_vocal'%}">Stimmbildung</a>
          <a href="{% url 'teaching:teaching_strings'%}">Streichinstrumente</a>
          <a href="{% url 'dance:schedule'%}">Tanz & Bewegung</a>
          <a href="{% url 'teaching:teaching_keys'%}">Tasteninstrumente</a>
          <a href="{% url 'teaching:teaching_picked'%}">Zupfinstrumente</a>
          
          <div class="mobile-section-divider">Weitere Angebote</div>
          <a href="{% url 'orgelunterricht' %}">Orgelunterricht</a>
          <a href="{% url 'midi_band' %}">MIDI Band</a>
        </div>
      </div>
      
      <!-- Kunstschule -->
      <div class="mobile-nav-group">
        <a class="mobile-main-heading single" href="{% url 'teaching:teaching_art'%}">
          Kunstschule
        </a>
      </div>
      
      <!-- Galerie -->
      <div class="mobile-nav-group">
        <a class="mobile-main-heading single" href="{% url 'gallery_view'%}">
          Galerie
        </a>
      </div>
      
      <!-- Über Uns Gruppe -->
      <div class="mobile-nav-group">
        <a class="mobile-main-heading" href="{% url 'teaching:all_teachers'%}">
          Über Uns
        </a>
        <div class="mobile-sub-items">
          <a href="{% url 'teaching:all_teachers'%}">Team</a>
          <a href="{% url 'history'%}">Geschichte</a>
          <a href="{% url 'blog_summary' %}">Blog</a>
        </div>
      </div>
      
      <!-- Kontakt & Info -->
      <div class="mobile-nav-group">
        <a class="mobile-main-heading single" href="{% url 'contact_email' %}">
          Kontakt
        </a>
      </div>
      
      <div class="mobile-nav-group">
        <a class="mobile-main-heading single" href="{% url 'teaching:teaching_prices'%}">
          Beiträge & Ermäßigungen
        </a>
      </div>
    </div>
  </div>
</header>